server:
  port: 9090
  multipart:
    enabled: true
    max-file-size: 90MB #90M
    max-request-size: 90MB

logging:
  level:
    ROOT: DEBUG
    com.example.trello: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 41689729816-av3tl6knb8sf7dhpp6d41fdlhtqegf4n.apps.googleusercontent.com
            clientSecret: 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
            #              /oauth2/authorization/google
            scope:
              - email
              - profile

  mail:
    host: smtp.gmail.com
    username: thanhlonghoangdao1101@gmail.com
    password: kqstzinevehphcfd
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  security:
    jwt:
      secretKey: de6aaeabadeccc598160172044da9c566242ae3b
      tokenValidityMilliseconds: 86400000
      rememberMeTokenValiditySeconds: 25920000000



